# Site settings
title: Wayne Tsai
email: wayne@tsai.co
description: > # this means to ignore newlines until "baseurl:"
    Hi there, I'm Wayne. Co-founder of TrackDota, now working with a great team at Dotabuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.tsai.co" # the base hostname & protocol for your site
twitter_username: watbe
github_username: watbe
permalink: /blog/:title

# Build settings
markdown: kramdown
