# Site settings
title: Wayne Tsai
email: me@tsai.co
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.tsai.co" # the base hostname & protocol for your site
twitter_username: watbe
github_username: watbe
permalink: /blog/:title

# Build settings
markdown: kramdown
